# Generated by Django 5.2.6 on 2025-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_degrees/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve this doctor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
