# Generated by Django 5.2.6 on 2025-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_rename_title_profile_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=False, help_text="Doctor's availability toggle"),
        ),
    ]
