# Generated by Django 5.2.6 on 2025-11-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_moodentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
